#!/bin/bash
# Keep BSC's grid workers topped up (cron, 2026-07-22 user decision).
#
# Each ms_grid job = 1 node = 4 H100s, walltime 5h45. The user chose 32
# concurrent GPUs = 8 jobs; this holds 8 in flight (running + pending) so a
# finishing job is replaced without a gap, and STOPS on its own once the
# shared worklist is drained (counter >= N) or a stop-file is dropped.
#
# Runs on the LOCAL machine (which has the BSC ssh key). Idempotent and safe
# to fire every 15 min: it only ever tops UP to the target, never past it.
set -uo pipefail

# Login-host FAILOVER (added 2026-08-01, during the RHEL 9.6 migration):
# alogin1 went unreachable for hours while it was migrated and every keeper
# tick failed with rc=255, so nothing was submitted. Try each host in turn and
# use the first that answers. alogin2 migrated first, so it leads.
BSC_HOSTS=${BSC_HOSTS:-"ub881905@alogin2.bsc.es ub881905@alogin1.bsc.es"}
BSC=""
for h in $BSC_HOSTS; do
    if timeout 25 ssh -o BatchMode=yes -o ConnectTimeout=15 "$h" true 2>/dev/null; then
        BSC="$h"; break
    fi
done
MS=/gpfs/scratch/ub234/momentstem
TARGET=8                                   # 8 jobs x 4 GPUs = 32 concurrent
LOG=$HOME/projects/MomentsCNNEncoder/logs/bsc_keeper.log
STAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

log() { echo "$STAMP $*" >> "$LOG"; }

if [ -z "$BSC" ]; then
    log "rc=255 :: NO LOGIN HOST REACHABLE (tried: $BSC_HOSTS)"
    echo "no login host reachable" >&2
    exit 255
fi

# One remote round-trip: report drained?/count, and submit the shortfall.
out=$(timeout 120 ssh -o BatchMode=yes -o ConnectTimeout=30 "$BSC" bash -s <<REMOTE 2>&1
set -uo pipefail
MS=$MS
TARGET=$TARGET
[ -f "\$MS/STOP_KEEPER" ] && { echo "STATE stopped-by-file"; exit 0; }
N=\$(wc -l < "\$MS/worklist.bsc")
CTR=\$(cat "\$MS/queue.counter" 2>/dev/null || echo 0)
# big lane: hold up to TWO 24h ms_big jobs in flight while worklist.big has
# unclaimed tasks (cnx >=25%, pathmnist/food101 @100%, SSL-at-scale)
NBIG=\$(wc -l < "\$MS/worklist.big" 2>/dev/null || echo 0)
CBIG=\$(cat "\$MS/queue.counter.big" 2>/dev/null || echo 0)
BIGJOBS=\$(squeue -u ub881905 -h -n ms_big -t R,PD -o "%i" | wc -l)
if [ "\$CBIG" -ge "\$NBIG" ] && [ "\$BIGJOBS" -eq 0 ] && [ "\$NBIG" -gt 0 ] \
   && [ ! -f "\$MS/BIG_COMPLETE" ]; then
    # Big-lane RECONCILE (added 2026-07-27 after 53 walltime orphans): the
    # counter advances on CLAIM with no retry, exactly like the normal lane,
    # but the normal reconcile EXCLUDES big configs -- so big cells lost to
    # the 24h walltime were never re-attempted. Regenerate worklist.big from
    # what is still missing among the big configs. CAVEAT: make_missing only
    # scans configs/grid/, so configs/diagnostics/ big cells (vitenv, all
    # complete 2026-07-27) are not regenerated by this path.
    cd "\$MS/repo"
    [ -f "\$MS/env.sh" ] && source "\$MS/env.sh" >/dev/null 2>&1
    grep -o "configs/[^ ]*\.yaml" "\$MS/worklist.big" | sort -u > "\$MS/.bigcfgs"
    # Run the generator SEPARATELY and check its exit status. Piping it
    # straight into grep hid failures behind grep's status, and "no output"
    # was then read as "nothing missing" -> BIG_COMPLETE -> lane stops
    # forever. Same silent-guard class as the pretrain whitelist bugs.
    if ! OUT="\$MS/runs" python scripts/make_missing_worklist.py --split all \
            --extra-configs "\$MS/.diagcfgs" \
            > "\$MS/.missing.big.raw" 2> "\$MS/.missing.big.err"; then
        echo "STATE ERROR big-reconcile: generator FAILED, not declaring complete"
        head -3 "\$MS/.missing.big.err" | sed 's/^/  /'
        exit 1
    fi
    grep -Ff "\$MS/.bigcfgs" "\$MS/.missing.big.raw" > "\$MS/worklist.big.new"
    MB=\$(grep -c . "\$MS/worklist.big.new")   # grep -c prints 0 itself on empty
    if [ "\$MB" -eq 0 ]; then
        rm -f "\$MS/worklist.big.new"; touch "\$MS/BIG_COMPLETE"
        echo "STATE big-complete: 0 big cells missing"
    else
        mv "\$MS/worklist.big.new" "\$MS/worklist.big"
        echo 0 > "\$MS/queue.counter.big"
        echo "STATE big-reconciled: \$MB cells missing -> new pass"
        NBIG=\$MB; CBIG=0
    fi
    cd "\$MS"
fi
# BIG target raised 2 -> 4 on 2026-08-05: the grid lane is essentially done
# (a handful of cheap cells) while the big lane now holds the 12 ImageNet64
# cells, which are the scientifically decisive ones. Also: workers cache the
# worklist length at start, so the 2 jobs running when in64 was APPENDED can
# never claim it -- more slots is what actually gets those cells moving.
if [ "\$CBIG" -lt "\$NBIG" ] && [ "\$BIGJOBS" -lt 4 ]; then
    # Cap like the grid lane (2026-08-07): a big job runs SLOTS*4 = 8 tasks
    # concurrently, so never hold more jobs than ceil(remaining/8) -- a
    # 3-task heal list does not need 4 four-GPU nodes, and every idle
    # queued job drags fair-share priority down for the whole group.
    REMBIG=\$(( NBIG - CBIG ))
    CAPBIG=\$(( (REMBIG + 7) / 8 ))
    NEEDBIG=\$(( CAPBIG - BIGJOBS ))
    if [ "\$NEEDBIG" -gt 0 ]; then
        for i in \$(seq 1 \$NEEDBIG); do
            sbatch "\$MS/bsc_big.sbatch" 2>&1 | sed 's/^/SUBMIT-BIG /'
        done
    fi
fi
CUR=\$(squeue -u ub881905 -h -n ms_grid -t R,PD -o "%i" | wc -l)
if [ "\$CTR" -ge "\$N" ]; then
    # Queue counter exhausted. RECONCILE: the counter advances on CLAIM with no
    # retry, so cells lost to walltime expiry are gaps. Regenerate the worklist
    # from what has NO final.json and start a fresh pass over just those. Only
    # do this when NO worker is live (CUR==0) so we never swap the file under a
    # worker mid-read; while workers drain we just wait.
    if [ "\$CUR" -gt 0 ]; then echo "STATE draining \$CTR/\$N, \$CUR still live"; exit 0; fi
    cd "\$MS/repo"                          # scripts + configs/grid live here
    [ -f "\$MS/env.sh" ] && source "\$MS/env.sh" >/dev/null 2>&1
    # cnx cells at >=25% exceed the 5h45 worker walltime and live in the
    # dedicated 24h big-cell lane (worklist.big / bsc_big.sbatch) -- keep
    # them OUT of the normal reconcile pass or they churn forever.
    # exclude every config that lives in the big lane (data-driven: the
    # big worklist itself is the source of truth, no pattern list to rot)
    grep -o "configs/[^ ]*\.yaml" "\$MS/worklist.big" | sort -u > "\$MS/.bigcfgs"
    # --split all: BSC owns the ENTIRE grid since 2026-07-23 (turing's queue
    # lane retired; its 2 GPUs run dedicated waves only)
    # Generator run separately + status-checked: a FAILED generator must never
    # be read as "nothing missing" (that would write GRID_COMPLETE and stop
    # the campaign permanently). See the big-lane note above.
    if ! OUT="\$MS/runs" python scripts/make_missing_worklist.py --split all \
            --extra-configs "\$MS/.diagcfgs" \
            > "\$MS/.missing.raw" 2> "\$MS/.missing.err"; then
        echo "STATE ERROR reconcile: generator FAILED, not declaring complete"
        head -3 "\$MS/.missing.err" | sed 's/^/  /'
        exit 1
    fi
    grep -vFf "\$MS/.bigcfgs" "\$MS/.missing.raw" > "\$MS/worklist.bsc.new"
    M=\$(grep -c . "\$MS/worklist.bsc.new")    # grep -c prints 0 itself on empty
    if [ "\$M" -eq 0 ]; then
        rm -f "\$MS/worklist.bsc.new"; touch "\$MS/GRID_COMPLETE"
        echo "STATE complete: 0 cells missing"; exit 0
    fi
    mv "\$MS/worklist.bsc.new" "\$MS/worklist.bsc"
    echo 0 > "\$MS/queue.counter"           # fresh pass over the gaps
    echo "STATE reconciled: \$M cells missing -> new pass"
    N=\$M; CTR=0
fi
NEED=\$(( TARGET - CUR ))
# Do not submit 8 four-GPU node-jobs for a handful of tasks. On 2026-08-05 a
# 3-task worklist drew 8 jobs every 15 min, each exiting instantly with
# "queue drained" -- 24 node-jobs submitted in 45 minutes to run 3 cells.
# One job already has 4 GPUs, so cap the ask at ceil(remaining / 4).
REM=\$(( N - CTR ))
[ "\$REM" -lt 0 ] && REM=0
CAP=\$(( (REM + 31) / 32 ))     # a job runs SLOTS*4 = 32 tasks at once
[ "\$NEED" -gt "\$CAP" ] && NEED=\$CAP
echo "STATE feeding ctr=\$CTR/\$N running_or_pending=\$CUR need=\$NEED (remaining=\$REM)"
[ "\$NEED" -le 0 ] && exit 0
cd "\$MS"
for i in \$(seq 1 "\$NEED"); do
    sbatch "\$MS/bsc_worker.sbatch" 2>&1 | sed 's/^/SUBMIT /'
done
REMOTE
)
rc=$?
log "host=$BSC rc=$rc :: $(echo "$out" | tr '\n' '|')"
echo "$out"
exit $rc
