"""Emit the recurring paper numbers as LaTeX macros, derived from the records.

WHY THIS EXISTS. Across three review rounds the same defect recurred: a
number stated in prose drifted from the table or the record it came from.
Round 1 had six of them. Round 3 had the ViT baseline (61.4 typed as 62.7,
which is the above-crossing sign rate from a different table), the residual
spread (2.2 in two places, 2.1 in a third -- both roundings of 2.15), and a
GPU-hour split that summed to 3,339 against a stated 3,341. Each was fixed
individually as it was found, which is why it kept happening.

A number that appears in more than one place, or that a reader could check
against a table, is emitted here as a macro and used by name. It then cannot
drift, because prose and table read the same definition. Numbers that appear
exactly once and are inherently local stay inline.

    python scripts/make_paper_numbers.py > paper/tables/numbers.tex

The compute figures are recomputed from every retained run record rather than
carried forward, so the device split sums to the total by construction --
that is the round 3 NB1 defect, removed at the source rather than corrected.
"""
import csv
import glob
import json
import os
import sys
from decimal import Decimal, ROUND_HALF_UP

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "analysis"))

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Device thermal design power in watts, an UPPER bound on sustained draw.
# MareNostrum5's accelerated partition is H100 64GB SXM at 700W, not the 400W
# PCIe part; using the PCIe figure understates the energy by ~40%.
TDP = {"H100": 700.0, "H100 NVL": 400.0, "H200 NVL": 600.0, "RTX 3090": 350.0}
PUE = 1.2                 # data-center power usage effectiveness
CARBON = 0.17             # kg CO2eq per kWh, Spanish grid


def device_class(name):
    """Group the recorded GPU names into the classes the paper reports."""
    n = (name or "").upper()
    if "3090" in n:
        return "RTX 3090"
    if "H200" in n:
        return "H200 NVL"
    if "NVL" in n:
        return "H100 NVL"
    return "H100"


def compute():
    """GPU-hours per device class, and the energy that follows, from records."""
    hours, runs = {}, 0
    # runs/ and runs_ckptfix/ are real measurements; runs_smoke/ holds
    # 1-epoch pre-flight runs and is deliberately excluded.
    paths = (glob.glob(os.path.join(ROOT, "runs", "*", "seed*", "final.json")) +
             glob.glob(os.path.join(ROOT, "runs_ckptfix", "*", "seed*", "final.json")))
    for path in paths:
        try:
            with open(path) as f:
                r = json.load(f)
        except Exception:
            continue
        runs += 1
        w = r.get("wall_seconds")
        if not w:
            continue
        hours[device_class(r.get("gpu_name"))] = \
            hours.get(device_class(r.get("gpu_name")), 0.0) + w / 3600.0
    kwh = sum(h * TDP.get(d, 400.0) / 1000.0 for d, h in hours.items()) * PUE
    return hours, runs, kwh


def num(x):
    return f"{x:,}".replace(",", "{,}")


def dec(x, places=1):
    """Round half UP, the convention a reader checking arithmetic assumes.

    Python's default rounds half to EVEN, which silently turned 75.25 into
    75.2 in prose while the table carried 75.3, and 2.15 into 2.1 in one
    section and 2.2 in another. Both were reported as inconsistencies. Fixing
    the rounding rule once removes the whole class.
    """
    q = "1" if places == 0 else "0." + "0" * (places - 1) + "1"
    return str(Decimal(repr(float(x))).quantize(Decimal(q), rounding=ROUND_HALF_UP))


def main():
    out = ["% GENERATED by scripts/make_paper_numbers.py -- do not edit.",
           "% Every macro here is derived from the run records or the audit,",
           "% so a number used in prose cannot drift from the table beside it."]

    def macro(name, value, note=""):
        out.append(f"\\newcommand{{\\{name}}}{{{value}}}"
                   + (f"  % {note}" if note else ""))

    # ---- the sign-law audit, the single source for every count in Sec. 4 ----
    import audit_law_paired as ALP
    rows = ALP.load(os.path.join(ROOT, "runs"),
                    os.path.join(ROOT, "results", "all_results.csv"))
    LO, HI = 31.8, 40.3
    n_scope = len(rows)
    bracket = [r for r in rows if LO <= r["base"] <= HI]
    rest = [r for r in rows if not (LO <= r["base"] <= HI)]
    res = [r for r in rest if r["sem"] > 0 and abs(r["ro"]) > 2 * r["sem"]]
    unres = [r for r in rest if r not in res]
    ok = [r for r in res
          if (r["base"] < LO and r["ro"] < 0) or (r["base"] > HI and r["ro"] > 0)]
    macro("auditScope", num(n_scope))
    macro("auditResolvable", num(len(res)))
    macro("auditCorrect", num(len(ok)))
    macro("auditWrong", num(len(res) - len(ok)))
    macro("auditUnresolved", num(len(unres)))
    macro("auditBracket", num(len(bracket)))
    macro("auditRate", dec(100.0 * len(ok) / len(res)))
    # Take the residual spread from the audit's OWN output rather than
    # recomputing it here: two implementations of one statistic is exactly how
    # 2.1 and 2.2 came to coexist in the manuscript.
    import io, contextlib, re as _re
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        ALP.main() if hasattr(ALP, "main") else None
    m = _re.search(r"residual SD at fixed baseline\s*:\s*([\d.]+)", buf.getvalue())
    assert m, "audit did not report a residual SD"
    macro("auditResidSD", dec(m.group(1)), "residual spread at fixed baseline")

    # ---- compute and carbon, recomputed so the split sums to the total ----
    hours, runs, kwh = compute()
    total = sum(hours.values())
    macro("computeRuns", num(runs))
    # The CELL count is quoted in the abstract, the highlights, the intro and
    # Data Availability. It was hardcoded in all of them and went stale the
    # moment the ImageNet envelope landed, so it is generated now: a number the
    # paper repeats in five places is exactly the number that must not drift.
    with open(os.path.join(ROOT, "results", "all_results.csv")) as _f:
        n_cells = sum(1 for _ in csv.DictReader(_f))
    macro("computeCells", num(n_cells), "rows in results/all_results.csv")
    macro("computeGpuHours", num(int(round(total))))
    for dev, key in (("H100", "computeHhundred"), ("H100 NVL", "computeHnvl"),
                     ("H200 NVL", "computeHtwo"), ("RTX 3090", "computeAmpere")):
        macro(key, num(int(round(hours.get(dev, 0.0)))))
    # The two NVL classes are reported as one term in the paper.
    macro("computeNvl", num(int(round(hours.get("H100 NVL", 0.0)
                                      + hours.get("H200 NVL", 0.0)))))
    macro("computeKwh", num(int(round(kwh))))
    macro("computeCarbon", num(int(round(kwh * CARBON))))
    macro("computePerRun", dec(kwh * CARBON * 1000.0 / max(runs, 1), 0))

    # ---- headline cells that appear in prose AND in a table ----
    acc = {}
    with open(os.path.join(ROOT, "results", "all_results.csv")) as f:
        for r in csv.DictReader(f):
            acc[r["cell"]] = r
    best = acc["diagdeit_aux_100pct"]
    base = acc["diagdeit_none_100pct"]
    macro("vitBest", dec(best['acc_mean']),
          "DeiT aug + prior, CIFAR-100 100%")
    macro("vitBestBase", dec(base['acc_mean']),
          "same recipe without the prior")
    macro("vitBestDelta", dec(best['delta']),
          "must equal vitBest - vitBestBase")

    # ---- dense prediction, from analysis/aggregate_dense.py's tables ----
    # Same discipline as above: the dense section quotes these macros rather
    # than transcribing numbers, so prose cannot drift from the CSVs. Absolute
    # AND relative delta are both exported, because absolute mIoU is not
    # comparable across populations whose baselines differ eightfold -- reading
    # it as if it were is what produced a "13x label-space collapse" that was
    # really ~1.6x.
    dres, dlaw = {}, {}
    dr = os.path.join(ROOT, "results", "dense_results.csv")
    dl = os.path.join(ROOT, "results", "dense_law.csv")
    if os.path.exists(dr):
        with open(dr) as f:
            for r in csv.DictReader(f):
                dres[(r["population"], int(r["pct"]))] = r
    if os.path.exists(dl):
        with open(dl) as f:
            for r in csv.DictReader(f):
                dlaw[(r["population"], int(r["pct"]))] = r
    if dres:
        macro("denseCells", num(len(dres) * 6),
              "216 = 6 populations x 6 fractions x 2 arms x 3 seeds")
        macro("densePops", num(len({k[0] for k in dres})))
        v = dres[("voc", 1)]
        macro("denseVocOneDelta", dec(float(v["delta_miou"]), 2),
              "D4: dense at ~5 images/class")
        macro("denseVocOneRel", dec(float(v["delta_rel_pct"]), 1))
        v = dres[("voc", 25)]
        macro("denseVocPeak", dec(float(v["delta_miou"]), 2), "voc envelope peak")
        v = dres[("voc", 100)]
        macro("denseVocFull", dec(float(v["delta_miou"]), 2))
        macro("denseVocFullRel", dec(float(v["delta_rel_pct"]), 1))
        v = dres[("pascalcontext", 100)]
        macro("densePcFull", dec(float(v["delta_miou"]), 2),
              "same pixels as voc, 254 classes not 21")
        macro("densePcFullRel", dec(float(v["delta_rel_pct"]), 1))
        rel = [abs(float(r["delta_rel_pct"])) for k, r in dres.items()
               if k[1] <= 25 and r["delta_rel_pct"] != ""]
        macro("denseRelLo", dec(min(rel), 0))
        macro("denseRelHi", dec(max(rel), 0))
    if dlaw:
        res = [r for r in dlaw.values() if r["resolvable"] == "True" and r["predicted_sign"]]
        ok = [r for r in res if r["sign_as_predicted"] == "True"]
        macro("denseLawCells", num(len(dlaw)))
        macro("denseLawResolvable", num(len(res)))
        macro("denseLawCorrect", num(len(ok)))
        macro("denseLawBracket",
              num(len([r for r in dlaw.values() if r["branch"] == "inside"])))
        macro("denseLawUnres",
              num(len([r for r in dlaw.values() if r["resolvable"] != "True"])))
        pa = [float(r["baseline_pixel_acc"]) for r in res]
        macro("denseLawPixLo", dec(min(pa), 0))
        macro("denseLawPixHi", dec(max(pa), 0))

    print("\n".join(out))


if __name__ == "__main__":
    main()
