"""Emit the recurring paper numbers as LaTeX macros, derived from the records.

WHY THIS EXISTS. Across three review rounds the same defect recurred: a
number stated in prose drifted from the table or the record it came from.
Round 1 had six of them. Round 3 had the ViT baseline (61.4 typed as 62.7,
which is the above-crossing sign rate from a different table), the residual
spread (2.2 in two places, 2.1 in a third -- both roundings of 2.15), and a
GPU-hour split that summed to 3,339 against a stated 3,341. Each was fixed
individually as it was found, which is why it kept happening.

A number that appears in more than one place, or that a reader could check
against a table, is emitted here as a macro and used by name. It then cannot
drift, because prose and table read the same definition. Numbers that appear
exactly once and are inherently local stay inline.

    python scripts/make_paper_numbers.py > paper/tables/numbers.tex

The compute figures are recomputed from every retained run record rather than
carried forward, so the device split sums to the total by construction --
that is the round 3 NB1 defect, removed at the source rather than corrected.
"""
import csv
import glob
import json
import os
import statistics
import sys
from decimal import Decimal, ROUND_HALF_UP

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "analysis"))

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Device thermal design power in watts, an UPPER bound on sustained draw.
# MareNostrum5's accelerated partition is H100 64GB SXM at 700W, not the 400W
# PCIe part; using the PCIe figure understates the energy by ~40%.
TDP = {"H100": 700.0, "H100 NVL": 400.0, "H200 NVL": 600.0, "RTX 3090": 350.0}
PUE = 1.2                 # data-center power usage effectiveness
CARBON = 0.17             # kg CO2eq per kWh, Spanish grid


def device_class(name):
    """Group the recorded GPU names into the classes the paper reports."""
    n = (name or "").upper()
    if "3090" in n:
        return "RTX 3090"
    if "H200" in n:
        return "H200 NVL"
    if "NVL" in n:
        return "H100 NVL"
    return "H100"


def compute():
    """GPU-hours per device class, and the energy that follows, from records."""
    hours, runs = {}, 0
    # runs/ and runs_ckptfix/ are real measurements; runs_smoke/ holds
    # 1-epoch pre-flight runs and is deliberately excluded. runs_bscpull/ holds
    # cells pulled from the cluster and never mirrored into runs/; it was
    # missing here exactly as it was missing from the results exporter (found
    # 2026-08-20), so 60 runs of wall-clock went uncounted. It is scanned LAST
    # and deduplicated on (cell, seed) because 57 of its 117 records are
    # byte-identical mirrors of runs/ copies and would otherwise double-count.
    # runs_turing/ is fully mirrored into runs/ and adds nothing (checked, not
    # assumed).
    paths = (glob.glob(os.path.join(ROOT, "runs", "*", "seed*", "final.json")) +
             glob.glob(os.path.join(ROOT, "runs_ckptfix", "*", "seed*", "final.json")) +
             glob.glob(os.path.join(ROOT, "runs_bscpull", "*", "seed*", "final.json")))
    seen = set()
    for path in paths:
        parts = path.split(os.sep)
        cell_seed = (parts[-3], parts[-2])
        if cell_seed in seen:
            continue
        seen.add(cell_seed)
        try:
            with open(path) as f:
                r = json.load(f)
        except Exception:
            continue
        runs += 1
        w = r.get("wall_seconds")
        if not w:
            continue
        hours[device_class(r.get("gpu_name"))] = \
            hours.get(device_class(r.get("gpu_name")), 0.0) + w / 3600.0
    kwh = sum(h * TDP.get(d, 400.0) / 1000.0 for d, h in hours.items()) * PUE
    return hours, runs, kwh


def num(x):
    return f"{x:,}".replace(",", "{,}")


def dec(x, places=1):
    """Round half UP, the convention a reader checking arithmetic assumes.

    Python's default rounds half to EVEN, which silently turned 75.25 into
    75.2 in prose while the table carried 75.3, and 2.15 into 2.1 in one
    section and 2.2 in another. Both were reported as inconsistencies. Fixing
    the rounding rule once removes the whole class.
    """
    q = "1" if places == 0 else "0." + "0" * (places - 1) + "1"
    return str(Decimal(repr(float(x))).quantize(Decimal(q), rounding=ROUND_HALF_UP))


def main():
    out = ["% GENERATED by scripts/make_paper_numbers.py -- do not edit.",
           "% Every macro here is derived from the run records or the audit,",
           "% so a number used in prose cannot drift from the table beside it."]

    def macro(name, value, note=""):
        out.append(f"\\newcommand{{\\{name}}}{{{value}}}"
                   + (f"  % {note}" if note else ""))

    # ---- the sign-law audit, the single source for every count in Sec. 4 ----
    import audit_law_paired as ALP
    rows = ALP.load(os.path.join(ROOT, "runs"),
                    os.path.join(ROOT, "results", "all_results.csv"))
    LO, HI = 31.8, 40.3
    n_scope = len(rows)
    bracket = [r for r in rows if LO <= r["base"] <= HI]
    rest = [r for r in rows if not (LO <= r["base"] <= HI)]
    res = [r for r in rest if r["sem"] > 0 and abs(r["ro"]) > 2 * r["sem"]]
    unres = [r for r in rest if r not in res]
    ok = [r for r in res
          if (r["base"] < LO and r["ro"] < 0) or (r["base"] > HI and r["ro"] > 0)]
    # The widest population Table 7 narrows FROM: every paired cell carrying
    # both Delta and G at >=3 seeds, regardless of intervention. It was a
    # hand-typed 1,660 in the manuscript with no script behind it (and the
    # hand-count was wrong), which is precisely the drift these macros exist to
    # stop. Same criterion export_results_csv.py reports on its own last line.
    n_all = 0
    with open(os.path.join(ROOT, "results", "all_results.csv")) as fh:
        for r in csv.DictReader(fh):
            if (r.get("baseline_cell") and r.get("delta") and r.get("G")
                    and int(r.get("n_seeds") or 0) >= 3):
                n_all += 1
    # DELIBERATELY NOT FILTERED TO <100%, unlike auditScope below, and the two
    # will therefore look inconsistent to anyone who does not know why. The
    # probe-ceiling rule forbids SPLITTING a 100% cell into G and readout; it
    # does not forbid REPORTING G, and both arms are probed identically so the
    # gap stays valid. This row counts paired evaluations, so it legitimately
    # keeps cells the sign-law count drops.
    macro("auditAllPaired", num(n_all),
          "every intervention, >=3 seeds, 100% included; Table 7 row 1")
    macro("auditScope", num(n_scope))
    macro("auditResolvable", num(len(res)))
    macro("auditCorrect", num(len(ok)))
    macro("auditWrong", num(len(res) - len(ok)))
    macro("auditUnresolved", num(len(unres)))
    macro("auditBracket", num(len(bracket)))
    macro("auditRate", dec(100.0 * len(ok) / len(res)))
    # COVERAGE and the MAJORITY-SIGN BASELINE. Two referees independently asked
    # for these, and both are the right question: the resolvability rule is what
    # makes the audit meaningful, but it also decides which cells get a vote, so
    # the rate has to be read next to how many cells it speaks for. And an exact
    # binomial against a coin is not a null anyone would propose -- readout is
    # negative in most resolvable cells, so a constant "always negative" rule
    # already scores well and is the baseline the account has to beat.
    macro("auditCoverage", dec(100.0 * len(res) / n_scope),
          "resolvable / scope; the audit's coverage")
    _neg = sum(1 for r in res if r["ro"] < 0)
    macro("auditMajority", dec(100.0 * max(_neg, len(res) - _neg) / len(res)),
          "always-predict-the-majority-sign baseline")
    # THE FULL TRANSFER-TAX POPULATION, rather than the three illustrative rows
    # of Table~\ref{tab:tax}: three cells cannot support a claim about a
    # regime. Every transfer cell carrying the prior at full auxiliary strength
    # is counted here, at >=3 seeds.
    # EXCLUSION, and it is load-bearing: the diagtaxlam_* family is the
    # SCHEDULE CONTROL for this very claim (reduced lambda0, and a delayed
    # onset at lambda0=1.0). Those cells are the arms that show the tax is
    # schedule-dependent, so counting them inside the population the sentence
    # describes would let the claim silently absorb its own control and turn
    # "not one is positive" false. They are reported separately in the text.
    _tax = []
    with open(os.path.join(ROOT, "results", "all_results.csv")) as _f:
        for _r in csv.DictReader(_f):
            if (_r.get("pretrained") == "yes" and _r.get("aux_target")
                    and _r.get("delta") and int(_r.get("n_seeds") or 0) >= 3
                    and not _r["cell"].startswith("diagtaxlam")):
                _tax.append(float(_r["delta"]))
    _tax.sort()
    macro("taxCells", num(len(_tax)), "transfer cells carrying the prior")
    macro("taxNegative", num(sum(1 for v in _tax if v < 0)))
    macro("taxWorst", dec(_tax[0], 1))
    # MEDIAN, not the upper of the two middle values. The previous form,
    # _tax[len(_tax) // 2], is wrong on an even-length list and reported -6.8
    # where the median of these 92 values is -7.0.
    macro("taxMedian", dec(statistics.median(_tax), 1))
    # THE RESCOPING DISCLOSURE (Section 4.2), generated rather than typed.
    # An earlier version of in_scope() tested the exporter's `pretrained`
    # column against the strings "true"/"1" while the exporter writes "yes",
    # so the ImageNet-transfer cells -- which the law's scope has excluded
    # since it was first stated -- were silently counted. Restoring the filter
    # moved the headline rate, so the manuscript reports the previous figure,
    # the excluded cells, and how those cells behave on their own. Recomputed
    # here under the OLD predicate so the two numbers cannot drift apart.
    #
    # THERE ARE NOW TWO REPAIRS, NOT ONE, AND THEY MUST NOT BE POOLED.
    # The 2026-08-18 pass restored the probe-ceiling rule (100% cells cannot
    # be split into G and readout). Differencing the current scope against
    # `prev` alone would attribute BOTH repairs to the `pretrained` bug and
    # report 153 excluded cells in a paragraph that names only the transfer
    # cells. So three scopes are computed and the two exclusions reported
    # separately:
    #   prev -> the true historical scope: pretrained bug present, 100% in
    #   mid  -> pretrained repaired, 100% still in (the 2026-08-17 state)
    #   rows -> both rules enforced (current)
    # giving rates 79.1% -> 85.7% -> 86.4% as two attributable steps.
    old_pred = ALP.in_scope
    _buggy_pretrained = lambda r: (
        r.get("aux_target") and not r.get("init_from")
        and str(r.get("pretrained", "")).lower() not in ("true", "1")
        and (r.get("stem") or "none") == "none")
    _hundred_in = lambda r: (
        r.get("aux_target") and not r.get("init_from")
        and not r.get("pretrained")
        and (r.get("stem") or "none") == "none")
    ALP.in_scope = _buggy_pretrained
    prev = ALP.load(os.path.join(ROOT, "runs"),
                    os.path.join(ROOT, "results", "all_results.csv"))
    ALP.in_scope = _hundred_in
    mid = ALP.load(os.path.join(ROOT, "runs"),
                   os.path.join(ROOT, "results", "all_results.csv"))
    ALP.in_scope = old_pred

    def _split(rr):
        rest_ = [r for r in rr if not (LO <= r["base"] <= HI)]
        res_ = [r for r in rest_ if r["sem"] > 0 and abs(r["ro"]) > 2 * r["sem"]]
        ok_ = [r for r in res_ if (r["base"] < LO and r["ro"] < 0)
               or (r["base"] > HI and r["ro"] > 0)]
        below = [r for r in res_ if r["base"] < LO]
        below_ok = [r for r in below if r["ro"] < 0]
        return res_, ok_, below, below_ok
    p_res, p_ok, p_below, p_below_ok = _split(prev)
    m_res, m_ok, m_below, m_below_ok = _split(mid)
    _, _, n_below, n_below_ok = _split(rows)
    key = lambda r: (r.get("cell"), r.get("dataset"), r.get("subset_pct"))
    keep = set(map(key, rows))
    keep_mid = set(map(key, mid))
    # repair 1: the transfer-tax cells the `pretrained` string test let in
    excl = [r for r in prev if key(r) not in keep_mid]
    e_res, e_ok, _, _ = _split(excl)
    # repair 2: the 100% cells the probe-ceiling rule refuses to split
    hexcl = [r for r in mid if key(r) not in keep]
    h_res, h_ok, h_below, _ = _split(hexcl)
    macro("auditPrevScope", num(len(prev)), "scope before the filter was restored")
    macro("auditPrevResolvable", num(len(p_res)))
    macro("auditPrevRate", dec(100.0 * len(p_ok) / len(p_res)))
    macro("auditPrevBelowRate", dec(100.0 * len(p_below_ok) / len(p_below)))
    macro("auditBelowRate", dec(100.0 * len(n_below_ok) / len(n_below)))
    macro("auditExclCells", num(len(excl)), "repair 1: ImageNet-transfer only")
    macro("auditExclResolvable", num(len(e_res)))
    macro("auditExclCorrect", num(len(e_ok)))
    macro("auditExclWrong", num(len(e_res) - len(e_ok)))
    macro("auditExclRate", dec(100.0 * len(e_ok) / len(e_res)))
    # The intermediate state, so the two repairs can be narrated as two steps
    # rather than one unattributable jump.
    macro("auditMidScope", num(len(mid)), "after repair 1, before repair 2")
    macro("auditMidResolvable", num(len(m_res)))
    macro("auditMidRate", dec(100.0 * len(m_ok) / len(m_res)))
    macro("auditMidBelowRate", dec(100.0 * len(m_below_ok) / len(m_below)))
    # repair 2 in the same shape as repair 1
    macro("auditHundredCells", num(len(hexcl)), "repair 2: cells at 100%")
    macro("auditHundredResolvable", num(len(h_res)))
    macro("auditHundredCorrect", num(len(h_ok)))
    macro("auditHundredWrong", num(len(h_res) - len(h_ok)))
    macro("auditHundredRate", dec(100.0 * len(h_ok) / len(h_res)))
    macro("auditHundredBelow", num(len(h_below)),
          "below-crossing cells repair 2 removes")
    # Take the residual spread from the audit's OWN output rather than
    # recomputing it here: two implementations of one statistic is exactly how
    # 2.1 and 2.2 came to coexist in the manuscript.
    import io, contextlib, re as _re
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        ALP.main() if hasattr(ALP, "main") else None
    m = _re.search(r"residual SD at fixed baseline\s*:\s*([\d.]+)", buf.getvalue())
    assert m, "audit did not report a residual SD"
    macro("auditResidSD", dec(m.group(1)), "residual spread at fixed baseline")

    # ---- compute and carbon, recomputed so the split sums to the total ----
    hours, runs, kwh = compute()
    total = sum(hours.values())
    macro("computeRuns", num(runs))
    # The CELL count is quoted in the abstract, the highlights, the intro and
    # Data Availability. It was hardcoded in all of them and went stale the
    # moment the ImageNet envelope landed, so it is generated now: a number the
    # paper repeats in five places is exactly the number that must not drift.
    with open(os.path.join(ROOT, "results", "all_results.csv")) as _f:
        n_cells = sum(1 for _ in csv.DictReader(_f))
    macro("computeCells", num(n_cells), "rows in results/all_results.csv")
    macro("computeGpuHours", num(int(round(total))))
    for dev, key in (("H100", "computeHhundred"), ("RTX 3090", "computeAmpere")):
        macro(key, num(int(round(hours.get(dev, 0.0)))))
    # The two NVL classes are reported as ONE term in the paper, so only the
    # sum is emitted. The per-class components were emitted too and never
    # printed, which is how a macro file grows figures nothing checks: an
    # unused macro cannot drift visibly, so it silently stops being audited.
    macro("computeNvl", num(int(round(hours.get("H100 NVL", 0.0)
                                      + hours.get("H200 NVL", 0.0)))))
    macro("computeKwh", num(int(round(kwh))))
    macro("computeCarbon", num(int(round(kwh * CARBON))))
    macro("computePerRun", dec(kwh * CARBON * 1000.0 / max(runs, 1), 0))

    # ---- headline cells that appear in prose AND in a table ----
    acc = {}
    with open(os.path.join(ROOT, "results", "all_results.csv")) as f:
        for r in csv.DictReader(f):
            acc[r["cell"]] = r
    best = acc["diagdeit_aux_100pct"]
    base = acc["diagdeit_none_100pct"]
    macro("vitBest", dec(best['acc_mean']),
          "DeiT aug + prior, CIFAR-100 100%")
    macro("vitBestBase", dec(base['acc_mean']),
          "same recipe without the prior")
    macro("vitBestDelta", dec(best['delta']),
          "must equal vitBest - vitBestBase")

    # ---- dense prediction, from analysis/aggregate_dense.py's tables ----
    # Same discipline as above: the dense section quotes these macros rather
    # than transcribing numbers, so prose cannot drift from the CSVs. Absolute
    # AND relative delta are both exported, because absolute mIoU is not
    # comparable across populations whose baselines differ eightfold -- reading
    # it as if it were is what produced a "13x label-space collapse" that was
    # really ~1.6x.
    dres, dlaw = {}, {}
    dr = os.path.join(ROOT, "results", "dense_results.csv")
    dl = os.path.join(ROOT, "results", "dense_law.csv")
    if os.path.exists(dr):
        with open(dr) as f:
            for r in csv.DictReader(f):
                dres[(r["population"], int(r["pct"]))] = r
    if os.path.exists(dl):
        with open(dl) as f:
            for r in csv.DictReader(f):
                dlaw[(r["population"], int(r["pct"]))] = r
    if dres:
        macro("denseCells", num(len(dres) * 6),
              "216 = 6 populations x 6 fractions x 2 arms x 3 seeds")
        macro("densePops", num(len({k[0] for k in dres})))
        v = dres[("voc", 1)]
        macro("denseVocOneDelta", dec(float(v["delta_miou"]), 2),
              "D4: dense at ~5 images/class")
        macro("denseVocOneRel", dec(float(v["delta_rel_pct"]), 1))
        v = dres[("voc", 25)]
        macro("denseVocPeak", dec(float(v["delta_miou"]), 2), "voc envelope peak")
        v = dres[("voc", 100)]
        macro("denseVocFull", dec(float(v["delta_miou"]), 2))
        macro("denseVocFullRel", dec(float(v["delta_rel_pct"]), 1))
        v = dres[("pascalcontext", 100)]
        macro("densePcFull", dec(float(v["delta_miou"]), 2),
              "same pixels as voc, 254 classes not 21")
        macro("densePcFullRel", dec(float(v["delta_rel_pct"]), 1))
        rel = [abs(float(r["delta_rel_pct"])) for k, r in dres.items()
               if k[1] <= 25 and r["delta_rel_pct"] != ""]
        macro("denseRelLo", dec(min(rel), 0))
        macro("denseRelHi", dec(max(rel), 0))
    if dlaw:
        res = [r for r in dlaw.values() if r["resolvable"] == "True" and r["predicted_sign"]]
        ok = [r for r in res if r["sign_as_predicted"] == "True"]
        macro("denseLawCells", num(len(dlaw)))
        macro("denseLawResolvable", num(len(res)))
        macro("denseLawCorrect", num(len(ok)))
        macro("denseLawBracket",
              num(len([r for r in dlaw.values() if r["branch"] == "inside"])))
        # The three groups must PARTITION the dense law cells, because the
        # prose adds them up: bracket + unresolved + resolvable = total. The
        # old test was `resolvable != "True"`, which also catches the
        # in-bracket rows and so double-counted them -- 2 + 21 + 9 = 32
        # against a stated 30. Exclude the bracket rows explicitly.
        macro("denseLawUnres",
              num(len([r for r in dlaw.values()
                       if r["resolvable"] != "True" and r["branch"] != "inside"])))
        pa = [float(r["baseline_pixel_acc"]) for r in res]
        macro("denseLawPixLo", dec(min(pa), 0))
        macro("denseLawPixHi", dec(max(pa), 0))

    # ---- detection, from analysis/aggregate_det.py -----------------------
    # The detection result is a null, which makes the discipline matter MORE
    # rather than less: a reader checking whether the zeros are really zeros
    # should find the same numbers in the prose, the table and the CSV.
    det = {}
    dp = os.path.join(ROOT, "results", "det_results.csv")
    if os.path.exists(dp):
        with open(dp) as f:
            for r in csv.DictReader(f):
                det[int(r["pct"])] = r
    if det:
        macro("detCells", num(len(det) * 6),
              "36 runs = 6 fractions x 2 arms x 3 seeds")
        macro("detCellCount", num(len(det) * 2),
              "a cell is a (config, fraction) pair, as in the dense tables")
        macro("detFloorPcts", " and ".join(f"{p}\\%" for p in sorted(det)
                                           if det[p]["ap50_interpretable"] != "True"),
              "fractions where BOTH arms fall under the 1.0 AP50 floor")
        v = det[1]
        macro("detOneDelta", dec(float(v["delta_ap50"]), 2))
        macro("detOneFgAcc", dec(float(v["none_fg_acc"]), 1),
              "baseline fg_acc at 1%: below the crossing bracket")
        macro("detOneGFgAcc", dec(float(v["G_fg_acc"]), 2),
              "the falsifier needed >= +1.5 here")
        v = det[10]
        macro("detTenDelta", dec(float(v["delta_ap50"]), 2), "the one nonzero cell")
        macro("detTenGFgIou", dec(float(v["G_fg_iou"]), 4),
              "the only resolvable G in the detection grid")
        macro("detTenGFgIouSem", dec(float(v["G_fg_iou_sem"]), 4))
        v = det[100]
        macro("detFullAPnone", dec(float(v["none_ap50"]), 1),
              "instrument check: the pre-recorded FPN conditional was <= 15")
        macro("detFullDelta", dec(float(v["delta_ap50"]), 2))
        # The probe's OWN AP50 at 1% is what makes the law untestable here:
        # it floors on the same side of the crossing where a negative readout
        # would have to be read. No fallback literal -- if the probe records
        # are missing the macro is absent and main.tex's staleness guard fires.
        v = det[1]
        if v.get("probe_ap50_none"):
            macro("detProbeOneAP", dec(float(v["probe_ap50_none"]), 2),
                  "the probe's own AP50 at 1%: floored, so no law cell")
            macro("detProbeLiftOne", dec(float(v["probe_fg_acc_none"]), 1),
                  "probe fg_acc at 1%, against the trained cell's own")

    # ---- imprint specificity, from analysis/imprint_specificity.py -------
    # The mechanistic claim quotes these rather than transcribing them, for the
    # same reason as everything else here: a number repeated in prose and a
    # table must come from one place.
    _imp = os.path.join(ROOT, "results", "imprint_specificity.json")
    if os.path.exists(_imp):
        import statistics as _st
        _d = json.load(open(_imp))
        def _grp(pred):
            g = [r for r in _d if pred(r)]
            return (len(g), _st.mean(r["align_gap"] for r in g),
                    _st.mean(r["G"] for r in g)) if g else (0, 0.0, 0.0)
        n, gap, G = _grp(lambda r: r["family"] == "moment prior" and "tap" not in r["cell"])
        macro("imprintPriorN", num(n)); macro("imprintPrior", dec(gap, 2))
        macro("imprintPriorG", dec(G, 2))
        n, gap, G = _grp(lambda r: r["family"] == "SimCLR init" and "aux" not in r["cell"])
        macro("imprintSSLN", num(n)); macro("imprintSSL", dec(gap, 2))
        macro("imprintSSLG", dec(G, 2), "larger than the prior's, by a different route")
        _, gap, _ = _grp(lambda r: r["family"] == "random target")
        macro("imprintRand", dec(gap, 2))
        _, gap, _ = _grp(lambda r: r["family"] == "moment prior" and "tap" in r["cell"])
        macro("imprintTap", dec(gap, 2), "same target, imposed at L1/L2")
        _, gap, _ = _grp(lambda r: "simclraux" in r["cell"])
        macro("imprintCombo", dec(gap, 2), "same SSL init, plus the target")

    # ---- CAM concentration, from analysis/cam_concentration.py -----------
    _cam = os.path.join(ROOT, "results", "cam_concentration.json")
    if os.path.exists(_cam):
        _c = json.load(open(_cam))[0]
        macro("camBase", dec(_c["gini_base"], 3))
        macro("camAux", dec(_c["gini_aux"], 3))
        macro("camDelta", dec(_c["delta"], 3), "whole test set, not the panel")
        macro("camN", num(_c["n_images"]))
        _sem = (_c["gini_base_sem"] ** 2 + _c["gini_aux_sem"] ** 2) ** 0.5
        macro("camSigma", dec(_c["delta"] / _sem, 1))

    # A sentinel the document checks. tables/numbers.tex is GENERATED and has to
    # travel with the sections that use its macros; when it does not, LaTeX fails
    # with "control sequence never \\def'ed", which says nothing about the cause.
    macro("numbersStamp", "ok", "presence checked by main.tex")

    print("\n".join(out))


if __name__ == "__main__":
    main()
