"""Emit the dataset/partition table from the FIXED subset index files.

Every fraction in this study is a precomputed, stratified index set stored in
data/subsets/<dataset>_<pct>pct.json, and every arm of every cell reads the
same file. Deriving the table from those files rather than from
round(pct * train_size) means the printed counts are what was actually
trained on, including the rounding the per-class stratified draw introduces.

The images-per-class figure is printed beside each count because it, not the
percentage, is what decides which regime a cell is in: 1% of CIFAR-10 is 50
images per class and 1% of Tiny-ImageNet is 5, and the study's findings differ
sharply between those.

Consistency is checked rather than assumed: the 50% subset must contain about
half of the declared training split, or the script fails. That catches a
mismatch between the split we cite and the indices we actually trained on.

  python scripts/make_partition_table.py > paper/tables/partitions.tex
"""

import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import data as data_mod

# (domain, label, subset-file prefix, key in data.NUM_CLASSES, train-pool size).
# The pool is what the subsets were actually drawn from, which is NOT always the
# dataset's headline training split, and the check below is what caught two
# places where the paper had cited the headline number instead:
#   DTD    -- the study follows the standard protocol and trains on train+val
#             (3,760 = 80/class), not the 1,880-image train split alone.
#   So2Sat -- the study trains on the v4 VALIDATION split (24,119) and tests on
#             the v4 test split, both held out from the training cities. The
#             352,366-image v4 training split is not used at all.
ROWS = [
    ("Photographic",   "CIFAR-10",      "krizhevsky2009cifar",     "cifar10",    "cifar10",       50_000),
    ("",               "CIFAR-100",     "krizhevsky2009cifar",     "cifar100",   "cifar100",      50_000),
    ("",               "STL-10",        "coates2011stl10",         "stl10",      "stl10",          5_000),
    ("",               "Tiny-ImageNet", "le2015tinyimagenet",      "tin",        "tin",          100_000),
    ("Satellite",      "EuroSAT",       "helber2019eurosat",       "eurosat",    "eurosat",       21_600),
    ("Multi-sensor",   "So2Sat LCZ42",  "zhu2020so2sat",           "so2sat_all", "so2sat_all",    24_119),
    ("Texture",        "DTD",           "cimpoi2014dtd",           "dtd",        "dtd",            3_760),
    ("Food",           "Food-101",      "bossard2014food101",      "food101",    "food101",       75_750),
    ("Histopathology", "PathMNIST",     "yang2023medmnist",        "pathmnist",  "pathmnist",     89_996),
    ("Fine-grained",   "CUB-200",       "wah2011cub",              "cub",        "cub",            5_994),
    # The subset-index prefix was None here, so load() returned {} and both rows
    # printed dashes at every fraction -- while data/subsets/imagenet{64,100}_*pct
    # .json have existed since the ImageNet envelope campaign and 84 configs were
    # trained from them. The table was therefore under-reporting the study's own
    # largest-scale envelopes, and its caption said so in words too.
    ("ImageNet scale", "ImageNet64",    "chrabaszcz2017downsampled", "imagenet64",  "imagenet64", 1_281_167),
    ("",               "ImageNet-100",  "deng2009imagenet",          "imagenet100", "imagenet100",  126_689),
]
SHOW = [1, 2, 3, 5, 7, 10, 15, 20, 25, 50]   # every fraction the grid uses
BATCH = 128   # frozen recipe, drop_last=True: a fraction yielding fewer than
              # one full batch has an EMPTY loader and cannot be trained at all


def load(prefix):
    """{pct: n} for every committed subset of one dataset."""
    out = {}
    if prefix is None:
        return out
    for path in glob.glob(f"data/subsets/{prefix}_*pct.json"):
        pct = os.path.basename(path)[len(prefix) + 1:-len("pct.json")]
        if pct.isdigit():
            with open(path) as f:
                out[int(pct)] = json.load(f)["n"]
    return out


def num(n):
    return f"{n:,}".replace(",", "{,}")


def main():
    print("% GENERATED by scripts/make_partition_table.py -- do not edit by hand.")
    print(r"\begin{table*}[pos=tbp]")
    print(r"\caption{Datasets and the partitions they were trained on. Counts are"
          r" read from the fixed subset index files every arm consumes, so they"
          r" carry the rounding of the per-class stratified draw. Parentheses"
          r" give images per class, which"
          r" sets a cell's regime. Relabeled controls and multi-source views reuse"
          r" their parent's indices exactly and share its row, which is why the"
          r" twenty dataset identities counted in the sign-law audit are not"
          r" twenty independent populations: five are relabeled controls of"
          r" their parent's pixels and four are band subsets of two parent"
          r" instruments, leaving eleven independent image sources. The two blanks"
          r" differ: $\times$ marks a fraction that \emph{cannot} be trained"
          r" under the frozen recipe, yielding fewer than one batch of 128"
          r" images; a dash marks one that is runnable but was not run.}")
    print(r"\label{tab:partitions}")
    # \mcell, not \makecell: a nested alignment advances colortbl's row
    # counter once per cell (so the banding stops alternating) and leaves a
    # white seam between columns. \mcell is a \parbox; see main.tex.
    # \zebra counts the two header rows AND the \cmidrule between them,
    # because a cmidrule also issues a \cr, so the first body row is 4.
    print(r"%% The numeric cells are \mcell, not \makecell -- a nested alignment"
          "\n%% here breaks the row banding; see the note in main.tex.")
    print(r"\centering\scriptsize")
    print(r"\setlength{\tabcolsep}{1.9pt}")
    print(r"\zebra{4}")
    print(r"\begin{tabular}{llrr" + "r" * (len(SHOW) + 1) + r"}")
    print(r"\toprule")
    print(r" & & & & \multicolumn{%d}{c}{training images at fraction (per class)} \\"
          % (len(SHOW) + 1))
    print(r"\cmidrule(l){5-%d}" % (5 + len(SHOW)))
    print(r"Domain & Dataset & Cls. & Px & " +
          " & ".join(f"{p}\\%" for p in SHOW) + r" & 100\% \\")
    print(r"\midrule")

    for domain, label, cite, prefix, key, train in ROWS:
        sizes = load(prefix)
        ncls = data_mod.NUM_CLASSES[key]
        px = data_mod.IMAGE_SIZE[key]

        # Verify the cited split against what was actually indexed.
        if 50 in sizes:
            ratio = sizes[50] / train
            if abs(ratio - 0.5) > 0.02:
                raise SystemExit(
                    f"{label}: 50% subset is {sizes[50]} = {ratio:.3f} of the "
                    f"declared split {train}; the cited split and the committed "
                    f"indices disagree.")

        cells = []
        for p in SHOW:
            n = sizes.get(p)
            if n is not None:
                cells.append(rf"\mcell{{{num(n)}}}{{({n / ncls:.0f})}}")
            elif round(train * p / 100) < BATCH:
                cells.append(r"$\times$")      # under one batch: unrunnable
            else:
                cells.append("--")             # runnable, not run
        cells.append(rf"\mcell{{{num(train)}}}{{({train / ncls:.0f})}}")
        print(f"{domain} & {label} \\citep{{{cite}}} & {ncls} & {px} & "
              + " & ".join(cells) + r" \\")

    print(r"\bottomrule")
    print(r"\end{tabular}")
    print(r"\end{table*}")


if __name__ == "__main__":
    main()
