"""Export the whole study to ONE Excel workbook.

    python analysis/export_excel.py [--out results/MomentStem_results.xlsx]

Sheets:
  README        what every sheet and column means (read this first)
  By portion    one row per CONFIGURATION, one column block per data portion
                -- each envelope reads left-to-right on a single line
  All cells     one row per cell (config name), full detail
  Law           the paired cells that have linear probes: Delta = G + readout,
                sorted by baseline accuracy so the sign-law crossing is visible
  Headline      only cells that obey the frozen recipe

Numbers are written as REAL numbers (not text), so sorting, filtering and
charting work. Deltas carry a red-white-green colour scale.
"""

import argparse
import os
import statistics as st
import sys

from openpyxl import Workbook
from openpyxl.formatting.rule import ColorScaleRule
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from export_results_csv import (TRAIN_SIZE, cfgget, config_key, config_label,
                                family_key, is_baseline, load_cells,
                                sem_of_diff)

HEAD_FILL = PatternFill("solid", fgColor="1F3864")
HEAD_FONT = Font(bold=True, color="FFFFFF")
GROUP_FILL = PatternFill("solid", fgColor="D9E1F2")


def style_header(ws, widths=None, freeze="A2"):
    for c in ws[1]:
        c.fill, c.font = HEAD_FILL, HEAD_FONT
        c.alignment = Alignment(horizontal="center", vertical="center",
                                wrap_text=True)
    ws.freeze_panes = freeze
    ws.auto_filter.ref = ws.dimensions
    ws.row_dimensions[1].height = 30
    for i, w in enumerate(widths or [], start=1):
        ws.column_dimensions[get_column_letter(i)].width = w



def write_grouped(ws, groups, rows, widths, freeze):
    """Two-level header: row 1 = group band (merged), row 2 = column names."""
    cols = [c for _, cs in groups for c in cs]
    ws.append([""] * len(cols))
    ws.append(cols)
    col = 1
    for title, cs in groups:
        if title:
            ws.merge_cells(start_row=1, start_column=col, end_row=1,
                           end_column=col + len(cs) - 1)
            ws.cell(row=1, column=col, value=title)
        else:
            for i in range(len(cs)):
                ws.merge_cells(start_row=1, start_column=col + i, end_row=2,
                               end_column=col + i)
                ws.cell(row=1, column=col + i, value=cs[i])
        col += len(cs)
    for d in rows:
        ws.append([d.get(c) for c in cols])
    for r in (1, 2):
        for c in ws[r]:
            c.fill, c.font = HEAD_FILL, HEAD_FONT
            c.alignment = Alignment(horizontal="center", vertical="center",
                                    wrap_text=True)
    ws.freeze_panes = freeze
    ws.auto_filter.ref = f"A2:{get_column_letter(len(cols))}{ws.max_row}"
    ws.row_dimensions[1].height = 28
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w
    return cols


def num(ws, row, col, value, fmt="0.00"):
    cell = ws.cell(row=row, column=col, value=value)
    if isinstance(value, (int, float)):
        cell.number_format = fmt
    return cell


def sheet_readme(wb, stats):
    ws = wb.create_sheet("README")
    ws.append(["MomentStem study - results workbook"])
    ws["A1"].font = Font(bold=True, size=14)
    rows = [
        [], ["Generated by", "python analysis/export_excel.py"],
        ["Cells", stats["cells"]], ["Configurations", stats["configs"]],
        ["Paired comparisons", stats["paired"]],
        ["Cells with a linear probe (G/readout)", stats["withG"]],
        [],
        ["SHEET", "WHAT IT CONTAINS"],
        ["By portion", "One row per CONFIGURATION; columns are DATA PORTIONS. "
                       "acc@ = test top-1; delta@ = gain vs that configuration's own "
                       "baseline; n@ = seeds. Baselines are listed first in each "
                       "(dataset, backbone) group."],
        ["All cells", "One row per cell (one config file = one experimental "
                      "condition), with its paired baseline, Delta, G and readout."],
        ["Law", "Only cells with a linear probe, sorted by baseline accuracy. "
                "Shows Delta = G + readout, the study's central claim."],
        ["Headline", "Only cells obeying the frozen recipe (SGD, 200 epochs, no "
                     "custom head/init/augmentation, name not prefixed 'diag')."],
        [],
        ["COLUMN", "MEANING"],
        ["acc_mean / acc_std", "Test top-1 (%), mean and std over seeds."],
        ["delta", "aux cell minus its baseline (percentage points). THE headline "
                  "quantity."],
        ["delta_sem", "Standard error of that difference (not the seed std)."],
        ["probe_mean", "Linear-probe accuracy: a frozen checkpoint's features read "
                       "out with the FULL labelled train set. A diagnostic - it uses "
                       "labels the cell never saw."],
        ["G", "Feature gain = probe(aux) - probe(baseline). How much better the "
              "features are once the classifier bottleneck is removed."],
        ["readout", "Delta - G. How much of the feature gain the cell's own "
                    "few-label classifier actually cashes in. Negative below ~30% "
                    "baseline accuracy, positive above (the 'sign law')."],
        ["is_headline", "yes = frozen recipe. no = diagnostic; NEVER mix these into "
                        "a headline table."],
        ["aux_lambda0 / _final", "The aux loss weight lambda at the start / end of "
                                 "training (champion: 1.0 -> exactly 0)."],
        ["cells", "The underlying run directory names, so any number is traceable "
                  "back to runs/<cell>/seed<N>/final.json."],
        [],
        ["NOTE", "Config labels are compact: aux(target@tap,Llambda0>lambdafinal), "
                 "stem(name,k), simclr-init, deit-aug, cosine-head, [adamw], [400ep]."],
        ["NOTE", "Definitions of every term live in docs/GLOSSARY.md."],
    ]
    for r in rows:
        ws.append(r)
    for r in ws.iter_rows(min_row=1, max_row=ws.max_row, max_col=1):
        if r[0].value in ("SHEET", "COLUMN", "NOTE"):
            r[0].font = Font(bold=True)
    ws.column_dimensions["A"].width = 26
    ws.column_dimensions["B"].width = 105
    for row in ws.iter_rows(min_col=2, max_col=2):
        for c in row:
            c.alignment = Alignment(wrap_text=True, vertical="top")
    return ws


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs-root", action="append", default=None)
    ap.add_argument("--out", default="results/MomentStem_results.xlsx")
    args = ap.parse_args()
    roots = [r for r in (args.runs_root or ["runs", "runs_turing"])
             if os.path.isdir(r)]
    cells = load_cells(roots)

    baselines = {}
    for cell, rec in cells.items():
        if is_baseline(rec["cfg"]):
            k = family_key(rec["cfg"])
            if k not in baselines or len(cells[baselines[k]]["seeds"]) < len(rec["seeds"]):
                baselines[k] = cell

    # ---- per-cell records ------------------------------------------------
    recs = []
    for cell, rec in sorted(cells.items()):
        cfg, accs = rec["cfg"], list(rec["seeds"].values())
        aux = cfgget(cfg, "moment_aux") or {}
        ds, pct = cfgget(cfg, "dataset"), cfgget(cfg, "subset_pct") or 100
        probe = rec["probes"].get("linear_probe.json")
        d = {"cell": cell, "config": config_label(cfg), "dataset": ds,
             "backbone": cfgget(cfg, "backbone"),
             "optimizer": (cfgget(cfg, "optimizer", "sgd") or "sgd").lower(),
             "epochs": cfgget(cfg, "epochs", 200),
             "subset_pct": pct,
             "n_images": int(round(TRAIN_SIZE.get(ds, 0) * pct / 100.0)) if ds in TRAIN_SIZE else None,
             "n_seeds": len(accs),
             "acc_mean": round(st.mean(accs), 3),
             "acc_std": round(st.stdev(accs), 3) if len(accs) > 1 else 0.0,
             "probe_mean": round(st.mean(probe), 3) if probe else None,
             "n_probe_seeds": len(probe) if probe else None,
             "is_headline": "yes" if (not cell.startswith("diag")
                                      and (cfgget(cfg, "optimizer", "sgd") or "sgd").lower() == "sgd"
                                      and cfgget(cfg, "epochs", 200) == 200
                                      and not cfgget(cfg, "head")
                                      and not cfgget(cfg, "init_from")
                                      and not cfgget(cfg, "augment")) else "no",
             "baseline_cell": None, "base_acc": None, "delta": None,
             "delta_sem": None, "G": None, "readout": None}
        b = baselines.get(family_key(cfg))
        if b and b != cell:
            baccs = list(cells[b]["seeds"].values())
            d["baseline_cell"], d["base_acc"] = b, round(st.mean(baccs), 3)
            d["delta"] = round(st.mean(accs) - st.mean(baccs), 3)
            s = sem_of_diff(accs, baccs)
            d["delta_sem"] = round(s, 3) if s != "" else None
            bp = cells[b]["probes"].get("linear_probe.json")
            if probe and bp:
                g = st.mean(probe) - st.mean(bp)
                d["G"] = round(g, 3)
                d["readout"] = round(d["delta"] - g, 3)
        recs.append(d)

    wb = Workbook()
    wb.remove(wb.active)

    # ---- Sheet: By portion ----------------------------------------------
    fams = {}
    for cell, rec in cells.items():
        cfg = rec["cfg"]
        pct = cfgget(cfg, "subset_pct") or 100
        accs = list(rec["seeds"].values())
        k = config_key(cfg)
        f = fams.setdefault(k, {"label": config_label(cfg),
                                "dataset": cfgget(cfg, "dataset"),
                                "backbone": cfgget(cfg, "backbone"),
                                "base": is_baseline(cfg), "by": {}, "cells": {}})
        b = baselines.get(family_key(cfg))
        delta = None
        if b and b != cell:
            delta = st.mean(accs) - st.mean(list(cells[b]["seeds"].values()))
        prev = f["by"].get(pct)
        if prev is None or prev["n"] < len(accs):
            f["by"][pct] = {"acc": st.mean(accs), "n": len(accs), "delta": delta}
            f["cells"][pct] = cell
    pcts = sorted({p for f in fams.values() for p in f["by"]})

    ws = wb.create_sheet("By portion")
    # TWO-LEVEL header: row 1 carries the metric name merged across its block,
    # row 2 the data portions. Beats repeating "acc@1%, acc@2%, ...".
    lead = ["configuration", "dataset", "backbone", "role"]
    groups = [("ACCURACY  (test top-1 %)", "acc"),
              ("DELTA  (vs own baseline, pts)", "delta"),
              ("SEEDS", "n")]
    ws.append([""] * (len(lead) + 3 * len(pcts) + 1))
    ws.append(lead + [f"{p}%" for _ in groups for p in pcts] + ["cells"])
    for i, name in enumerate(lead, start=1):          # id cols span both rows
        ws.merge_cells(start_row=1, start_column=i, end_row=2, end_column=i)
        ws.cell(row=1, column=i, value=name)
    col = len(lead) + 1
    for title, _ in groups:                            # metric spans its block
        ws.merge_cells(start_row=1, start_column=col, end_row=1,
                       end_column=col + len(pcts) - 1)
        ws.cell(row=1, column=col, value=title)
        col += len(pcts)
    ws.merge_cells(start_row=1, start_column=col, end_row=2, end_column=col)
    ws.cell(row=1, column=col, value="cells")

    frows = sorted(fams.values(), key=lambda f: (str(f["dataset"]), str(f["backbone"]),
                                                 0 if f["base"] else 1, f["label"]))
    for f in frows:
        r = [f["label"], f["dataset"], f["backbone"],
             "baseline" if f["base"] else "variant"]
        for _, kind in groups:
            for p in pcts:
                d = f["by"].get(p)
                if not d:
                    r.append(None)
                elif kind == "acc":
                    r.append(round(d["acc"], 2))
                elif kind == "delta":
                    r.append(round(d["delta"], 2) if d["delta"] is not None else None)
                else:
                    r.append(d["n"])
        r.append(" ".join(f["cells"][p] for p in sorted(f["cells"])))
        ws.append(r)

    for row in ws.iter_rows(min_row=3):
        if row[3].value == "baseline":
            for c in row:
                c.fill = GROUP_FILL
                c.font = Font(bold=True)
    d0 = len(lead) + len(pcts) + 1
    dl, dr = get_column_letter(d0), get_column_letter(d0 + len(pcts) - 1)
    ws.conditional_formatting.add(
        f"{dl}3:{dr}{ws.max_row}",
        ColorScaleRule(start_type="num", start_value=-5, start_color="F8696B",
                       mid_type="num", mid_value=0, mid_color="FFFFFF",
                       end_type="num", end_value=8, end_color="63BE7B"))
    for r in (1, 2):
        for c in ws[r]:
            c.fill, c.font = HEAD_FILL, HEAD_FONT
            c.alignment = Alignment(horizontal="center", vertical="center",
                                    wrap_text=True)
    ws.freeze_panes = "E3"
    ws.auto_filter.ref = (f"A2:{get_column_letter(ws.max_column)}{ws.max_row}")
    ws.row_dimensions[1].height = 30
    for i, w in enumerate([46, 14, 14, 10] + [8] * (3 * len(pcts)) + [70], start=1):
        ws.column_dimensions[get_column_letter(i)].width = w

    # ---- Sheet: All cells ------------------------------------------------
    GROUPS = [
        ("", ["cell", "config"]),
        ("SETUP", ["dataset", "backbone", "optimizer", "epochs"]),
        ("DATA", ["subset_pct", "n_images", "n_seeds"]),
        ("RESULT", ["acc_mean", "acc_std", "probe_mean", "n_probe_seeds"]),
        ("PAIRED COMPARISON  (vs own baseline)",
         ["baseline_cell", "base_acc", "delta", "delta_sem", "G", "readout"]),
        ("", ["is_headline"]),
    ]
    WIDTHS = [34, 40, 13, 13, 10, 8, 10, 10, 9, 10, 9, 11, 9, 26, 10, 9, 10, 9, 10, 11]
    ws = wb.create_sheet("All cells")
    cols = write_grouped(ws, GROUPS,
                         sorted(recs, key=lambda r: (str(r["dataset"]), str(r["backbone"]),
                                                     r["subset_pct"], r["cell"])),
                         WIDTHS, "C3")
    di = cols.index("delta") + 1
    ws.conditional_formatting.add(
        f"{get_column_letter(di)}3:{get_column_letter(di)}{ws.max_row}",
        ColorScaleRule(start_type="num", start_value=-5, start_color="F8696B",
                       mid_type="num", mid_value=0, mid_color="FFFFFF",
                       end_type="num", end_value=8, end_color="63BE7B"))

    # ---- Sheet: Law ------------------------------------------------------
    ws = wb.create_sheet("Law")
    LGROUPS = [
        ("", ["cell", "config"]),
        ("SETUP", ["dataset", "backbone", "subset_pct", "n_images"]),
        ("DELTA = G + READOUT", ["base_acc", "acc_mean", "delta", "delta_sem",
                                 "G", "readout"]),
        ("", ["n_seeds", "is_headline"]),
    ]
    write_grouped(ws, LGROUPS,
                  sorted([r for r in recs if r["G"] is not None],
                         key=lambda r: r["base_acc"]),
                  [34, 40, 13, 13, 10, 10, 10, 10, 9, 10, 9, 10, 9, 11], "C3")
    ri = [c for _, cs in LGROUPS for c in cs].index("readout") + 1
    ws.conditional_formatting.add(
        f"{get_column_letter(ri)}3:{get_column_letter(ri)}{ws.max_row}",
        ColorScaleRule(start_type="num", start_value=-4, start_color="F8696B",
                       mid_type="num", mid_value=0, mid_color="FFFFFF",
                       end_type="num", end_value=2, end_color="63BE7B"))

    # ---- Sheet: Headline -------------------------------------------------
    ws = wb.create_sheet("Headline")
    write_grouped(ws, GROUPS,
                  sorted([r for r in recs if r["is_headline"] == "yes"],
                         key=lambda r: (str(r["dataset"]), str(r["backbone"]),
                                        r["subset_pct"], r["cell"])),
                  WIDTHS, "C3")

    stats = {"cells": len(recs), "configs": len(frows),
             "paired": sum(1 for r in recs if r["delta"] is not None),
             "withG": sum(1 for r in recs if r["G"] is not None)}
    readme = sheet_readme(wb, stats)
    wb.move_sheet(readme, offset=-len(wb.sheetnames) + 1)

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    wb.save(args.out)
    print(f"wrote {args.out}: sheets={wb.sheetnames} "
          f"cells={stats['cells']} configs={stats['configs']} "
          f"paired={stats['paired']} withG={stats['withG']}")


if __name__ == "__main__":
    main()
