name: ablf_gaborlearn_calib
dataset: cifar100
subset_pct: 100
backbone: resnet18
epochs: 200
batch_size: 128
lr: 0.1
weight_decay: 0.0005
momentum: 0.9
num_workers: 8
small_input: true
pretrained: false
stem_kernel_size: 11
stem: gabor-learn
stem_calibrate: true
